services:
  db_server:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: