swagger: '2.0'
info:
  description: 'This is a sample Petstore User'
  version: 2.0.0
  title: NetApp's Microservice Petstore
  contact:
    email: charlie.mietzner@netapp.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: netappUser
basePath: /user
tags:
  - name: user
    description: Services related to the store's users/customers
schemes:
  - http

paths:

  /user:
    post:
      tags:
        - user
      summary: Registers one or more new users
      description: Adds user information to the store's registry.
      operationId: register_customer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: A list of one or more customer's info.
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      responses:
        '201':
          description: Successfully registered the new customer(s) with the store. The new customer info is returned.
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid customer input.
    get:
      tags:
        - user
      summary: Returns a list of customers
      description: Returns a list of all customers registered with the store.
      operationId: get
      produces:
        - application/json
      responses:
        '200':
          description: A list of all customers registered with the store.
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

  /user/{customerId}:
    get:
      tags:
        - user
      summary: Gets a customer by using their id property
      description: Returns a single customer, uniquely identified by their id property.
      operationId: get_user
      produces:
        - application/json
      parameters:
        - name: customerId
          in: path
          description: The id property of a customer registered with the store.
          required: true
          type: integer
      responses:
        '200':
          description: Returns a customer registered with the store under that id.
          schema:
            $ref: '#/definitions/User'
        '404':
          description: A customer with that id was not found.

definitions:

  User:
    type: object
    properties:
      id:
        description: A unique integer identifier for the customer generated by the server. Cannot be PATCHed or POSTed.
        type: integer
      name:
        type: string