#!/bin/bash
echo "Setting up Databases for microservices.."
echo "..."

echo "Setting up pet database"
docker exec -it my_postgres psql -U postgres -c "create database pet_db"
echo "..."

echo "Setting up user database"
docker exec -it my_postgres psql -U postgres -c "create database user_db"
echo "..."

echo "Initializing tables and values into Databases"
echo "..."

echo "Running Pet DB Script"
python pet-setup.py
echo "..."

echo "Running User DB Script"
python user-setup.py
echo "..."

echo "Done."