#!/bin/bash
echo "Setting up Databases for microservices.."
echo "..."

docker-compose up db_server & sleep 5

echo "Setting up pet database"
docker exec -it my_postgres psql -U postgres -c "create database pet_db"
echo "..."
echo "Setting up user database"
docker exec -it my_postgres psql -U postgres -c "create database user_db"
echo "..."

echo "Initializing tables and values into Databases"
echo "..."

echo "Running pet DB Script"
python pet-init.py
echo "..."
echo "Running user DB Script"
python user-init.py
echo "..."

echo "Done."