name: CI
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches: [master]

jobs: 
  job1:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
            python-version: '3.8'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r documentation/requirements.txt
      - name: Run full python file
        run: |
            cd api_gateway_microservice
            python controller.py
        
        