name: CI
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches: [master]

jobs: 
  job1:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
            python-version: '3.8'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r documentation/requirements.txt
            pip install psycopg2
      - name: Run Build.py
        run: |
            cd api_gateway_microservice
            python build.py
      - name: Run Docker-Compose build
        run: |
            cd api_gateway_microservice
            docker-compose build
      - name: Set up database
        run: |
            cd api_gateway_microservice
            bash dbsetup
      - name: Shut down containers
        run: |
            cd api_gateway_microservice
            docker-compose down
      - name: Run docker-compose up and display test results
        run: |
            cd api_gateway_microservice
            docker-compose up & sleep 120
            kill
        
        
